filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
filenames:
  - /var/log/nginx/access.log
labels:
  type: nginx
---
filenames:
  - /var/log/syslog
  - /var/log/kern.log
labels:
  type: syslog
---
filenames:
  - /var/log/audit/*.log
labels:
  type: auditd
